apiVersion: v2
name: 101application
description: 101 application
type: application
version: 1.0.0
appVersion: 1.16.0
dependencies:
  - name: nginx-ingress
    repository: "https://helm.nginx.com/stable"
    version: 0.10.1
    condition: global.nginx-ingress.enabled